name: CBMC Proofs
on:
  pull_request:

jobs:
  check-cbmc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install CBMC
        run: sudo apt-get install -y cbmc

      - name: Check Proofs
        run: |
          cbmc --version
          make -j proof
        shell: bash
