name: On Main Push
on:
  push:
    branches: [main]
jobs:
  book:
    if: ${{ vars.SKIP_FIREDANCER_CI != 'true' }}
    uses: ./.github/workflows/book.yml
    secrets: inherit
    permissions:
      contents: read
      pages: write
      id-token: write
